docker run -d \
  --name=code-server \
  -e PUID=999 \
  -e PGID=100 \
  -e TZ=America/Denver \
  -e PASSWORD=password `#optional` \
  -e HASHED_PASSWORD= `#optional` \
  -e SUDO_PASSWORD=password `#optional` \
  -e SUDO_PASSWORD_HASH= `#optional` \
  -e PROXY_DOMAIN=code-server.my.domain `#optional` \
  -e DEFAULT_WORKSPACE=/config/workspace `#optional` \
  -p 8443:8443 \
  -v /config:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/code-server:latest
